# -*- coding: utf-8 -*-
"""Data Analysis (Hotel Booking)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FVburnZCZXeYbX5tFfTdQayJ-EN8UmM-

# ***Importing Libraries***
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv("/content/hotel_bookings.csv")

df.head()

df.tail(10)

df.shape

df.columns

df.info()

df['reservation_status_date']=pd.to_datetime(df['reservation_status_date'])

df.info()

df.describe(include='object')

for col in df.describe(include='object').columns:
  print(col)
  print(df[col].unique())
  print("-"*50)

df.isnull().sum()

df.drop(['agent','company'],axis=1,inplace=True)
df.dropna(inplace=True)

df.isnull().sum()

df.describe()

df=df[df['adr']<5000]

df.describe()

"""# ***Data Analysis And Visualization***"""

cancelled_perc=df['is_canceled'].value_counts(normalize=True)
print(cancelled_perc)

plt.figure(figsize=(5,4))
plt.title("Reservation Status Count")
plt.bar(["Not Cancelled","Cancelled"],df['is_canceled'].value_counts(),edgecolor='k',width=0.7)
plt.show()

plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel',hue='is_canceled',data=df,palette='Blues')
plt.title("Reservation Status in Different Hotels",size=20)
plt.xlabel("Type Of Hotels")
plt.ylabel("No Of Reservations")
plt.show()

resort_hotel=df[df['hotel']=="Resort Hotel"]
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=="City Hotel"]
city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel = resort_hotel.groupby("reservation_status_date")[["adr"]].mean()
city_hotel = city_hotel.groupby("reservation_status_date")[["adr"]].mean()

plt.figure(figsize=(20,8))
plt.title("Average Daily Rate In City And Resort Hotels",fontsize=30)
plt.plot(resort_hotel.index,resort_hotel['adr'],label="Resort Hotel")
plt.plot(city_hotel.index,city_hotel['adr'],label="City Hotel")
plt.legend(fontsize=20)
plt.show()

# from matplotlib import legend
df['month']=df['reservation_status_date'].dt.month
plt.figure(figsize=(20,8))
ax1= sns.countplot(x='month',hue="is_canceled",data=df,palette='bright')
legend_labels,_=ax1.get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title("Reservation Status Per Month",size=30)
plt.xlabel('month')
plt.ylabel("Number Of Reservations")
plt.legend(["not canceled","canceled"])
plt.show()

new=df[df['is_canceled']== 1].groupby('month')[['adr']].sum().reset_index()

plt.figure(figsize=(15,8))
plt.title('ADR Per Month',fontsize=30)
sns.barplot(x='month',y='adr',data=new)
plt.show()

cancelled_data=df[df['is_canceled']==1]
top_10_country=cancelled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title("Top 10 Countries With Reservations Cancelled")
plt.pie(top_10_country,autopct='%.2f',labels=top_10_country.index)
plt.show()

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize=True)

cancelled_data['market_segment'].value_counts(normalize=True)

canceled_df_adr=cancelled_data.groupby("reservation_status_date")[['adr']].mean()
canceled_df_adr.reset_index(inplace=True)
canceled_df_adr.sort_values("reservation_status_date",inplace=True)

not_canceled_data=df[df['is_canceled']==0]
not_canceled_df_adr=not_canceled_data.groupby("reservation_status_date")[["adr"]].mean()
not_canceled_df_adr.reset_index(inplace=True)
not_canceled_df_adr.sort_values("reservation_status_date",inplace=True)

plt.figure(figsize=(20,6))
plt.title("Average Daily Rate",fontsize=30)
plt.plot(not_canceled_df_adr["reservation_status_date"],not_canceled_df_adr["adr"],label="Not Canceled")
plt.plot(canceled_df_adr["reservation_status_date"],canceled_df_adr["adr"],label="Canceled")
plt.legend()
plt.show()

canceled_df_adr=canceled_df_adr[(canceled_df_adr['reservation_status_date']>'2016') & (canceled_df_adr['reservation_status_date']<'2017-09')]
not_canceled_df_adr=not_canceled_df_adr[(not_canceled_df_adr['reservation_status_date']>'2016') & (not_canceled_df_adr['reservation_status_date']<'2017-09')]

plt.figure(figsize=(20,6))
plt.title("Average Daily Rate",fontsize=30)
plt.plot(not_canceled_df_adr["reservation_status_date"],not_canceled_df_adr["adr"],label="Not Canceled")
plt.plot(canceled_df_adr["reservation_status_date"],canceled_df_adr["adr"],label="Canceled")
plt.legend(fontsize=20)
plt.show()